[project]
name = 'Multiverse-Collaboration-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.multiversal-governance]
path = 'contracts/multiversal-governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-discrepancy-resolution]
path = 'contracts/reality-discrepancy-resolution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
